### ISSUE TITLE
Invalid bounding box values

### ISSUE THREAD

**Issue by RituYadav92** [mrnabati/RRPN#3]
HI, 
I am using the code you have provided for nuscenes to coco dataset conversion. It is working fine for small dataset(10 scenes) but when I tried for 85 scenes it is providing bounding boxes which are not in image size range(900,1600).
For example: "bbox": [1421.23, -221.73, 8121.54, 4666.13]   

could you please help me with the possible reason here?

**Comment by mrnabati** [comment]
I'll be updating the code for the full dataset soon, the current version was not tested on the full dataset.

**Comment by RituYadav92** [comment]
Ok, thanks.
