### ISSUE TITLE
Nuscenes to coco radar point mapping

### ISSUE THREAD

**Issue by RituYadav92** [mrnabati/RRPN#5]
Hi, 

Is there any shift intoduced in radar points( superimposed on image) while converting data to coco format?
I can see some extra radar point mapped on-road(in image) which were not present in nuscenes tutorial.

REgards,
Ritu Yadav

**Comment by mrnabati** [comment]
No Radar points are not shifted, they're just mapped to the image the way they are. Note that points from all 3 front Radars are mapped to the front camera image. The NuScenes tutorial might just be showing front center Radar points.

**Comment by RituYadav92** [comment]
I found the problem, it was in my code. Thanks.
