### ISSUE TITLE
Wrong lable in the infer result

### ISSUE THREAD

**Issue by punknownq** [mrnabati/RRPN#7]
Hi.Thank you for your work. I have got the output of the RRPN which is right. However, I got wrong lables after ran inference on the validation set images. Can you help me? For example, the person in the image is labeled "car" and the car in the image is labeled "person".

**Comment by mrnabati** [comment]
This is because of a mismatch between the category IDs in COCO and nuCOCO. 
A quick fix is to modify the "get_coco_dataset()" function in "detectron/datasets/dummy_datasets.py" and change "classes" from 

`classes = [
        '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane',
        'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant',
        'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse',
        'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack',
        'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis',
        'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove',
        'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass',
        'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich',
        'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake',
        'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv',
        'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
        'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase',
        'scissors', 'teddy bear', 'hair drier', 'toothbrush'
    ]`

to 

`classes = [
        '__background__', 'car', 'truck', 'person', 'motorcycle', '_',
        'bicycle', '_', 'bus'
    ]`

**Comment by punknownq** [comment]
Thank you for your reply!
