### ISSUE TITLE
File instances_val

### ISSUE THREAD

**Issue by albertchristian92** [mrnabati/RRPN#8]
Hello, thank you for your good works. 

Actually, I have a question about instances_val.json file. May I know from which nuscenes download data that you are using? Because when I setup the folder and convert to coco as you suggested, it resulted:
1. instances_mini_val.json
2. instances_test.json
3. instances_train.json

is it instances_val.json refer to instances_test.json?

Here, is the screenshot of the folder after I extracted:

![image](https://user-images.githubusercontent.com/12479762/94360190-2812ea00-00de-11eb-8b9a-4234621fd3a0.png)

I rename the folder to make it clear, as you wrote not overwrite it. 

Thank you very much.

**Comment by mrnabati** [comment]
Hi,

You should not create separate samples/sweeps folders for different dataset splits. Just extract all the dataset files in the same folder. Sample/sweep files for trainval and test splits have different filenames, so they will be extracted to the same sample/sweep folder but won't be overwritten.
For creating the coco instances, you should specify the dataset split using the `--split` arguments when running `nuscenes_to_coco.py`, and the split can be "mini_train", "mini_val", "train", "val" or "test". You then use the resulting "train" coco instances file (instances_train.json) for training and "val" instances file (instances_val.json) for validation.
Hope that answered your question.

**Comment by albertchristian92** [comment]
I  understand it clearly. Thank you for your information.
